export const letters = [
    { char: 'A', name: 'ey' },
    { char: 'B', name: 'bi' },
    { char: 'C', name: 'si' },
    { char: 'D', name: 'di' },
    { char: 'E', name: 'i' },
    { char: 'F', name: 'ef' },
    { char: 'G', name: 'dyi'},
    { char: 'H', name: 'eyts' },
    { char: 'I', name: 'ay' },
    { char: 'J', name: 'dyey' },
    { char: 'K', name: 'key' },
    { char: 'L', name: 'el' },
    { char: 'M', name: 'em' },
    { char: 'N', name: 'en' },
    { char: 'Ñ', name: 'enye' },
    { char: 'Ng', name: 'endyi' },
    { char: 'O', name: 'o' },
    { char: 'P', name: 'pi' },
    { char: 'Q', name: 'kyu' },
    { char: 'R', name: 'ar' },
    { char: 'S', name: 'es' },
    { char: 'T', name: 'ti' },
    { char: 'U', name: 'yu' },
    { char: 'V', name: 'vi' },
    { char: 'W', name: 'dobolyu' },
    { char: 'X', name: 'eks' },
    { char: 'Y', name: 'way' },
    { char: 'Z', name: 'zi' }
  ];